services:
  agendauni.api:
    build:
      context: ./api/AgendaUni.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AgendaUniDb;User Id=SA;Password=YourStrong@Password;Encrypt=False;
    depends_on:
      - sqlserver

  agendauni.web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - agendauni.api

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: